version: '3'
services:
  #------------------------
  #--- Jupyter Notebook ---
  #------------------------
  notebook:
    build:
      context: ./jupyter-notebook-docker
    ports:
      - "8888:8888"
    depends_on: 
      - mlflow
    environment: 
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes: 
      - file-store:/home/jovyan
  #----------------------
  #--- ML Flow Server ---
  #----------------------
  mlflow:
    build:
      context: ./ml-flow-docker
    expose: 
      - "5000"
    ports:
      - "5000:5000"
    depends_on: 
      - postgres
    environment:
      - ARTIFACT_AWS_BUCKET=mlflow-demo
  #-------------------
  #--- Postgres DB ---
  #-------------------
  postgres:
    build:
      context: ./postgres-docker
    restart: always
    environment:
        POSTGRES_PASSWORD: 'admin'
    ports: 
      - "5433:5432"
    volumes:
      - ./postgres-store:/var/lib/postgresql/data
  #-----------------
  #--- Influx DB ---
  #-----------------
  influx:
    image: influxdb:alpine
    ports: 
      - "8086:8086"
    environment: 
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=secret

volumes:
  postgres-store:
  influx-store:
  file-store:
